from .doubleCloudMAStrategy import DoubleCloudMAStrategy
from .doubleCloudMAStrategyV1 import DoubleCloudMAStrategyV1
from .MTFVWAPStrategy import MTFVWAPStrategy
from .MTFVWAPSingleCloudMAStrategy import MTFVWAPSingleCloudMAStrategy
from .singleCloudMAStrategy import SingleCloudMAStrategy
from .singleCloudMAStrategyV2 import SingleCloudMAStrategyV2
from .singleCloudMAStrategyV3 import SingleCloudMAStrategyV3
from .singleCloudMAStrategyV4 import SingleCloudMAStrategyV4
